#!/bin/sh
# Never checkin this file other than changes in BACKING_BUILD

# If you want to change location of default sandbox root, enable SANDBOXROOT
export SANDBOXROOT=$SBEROOT
# If you want to change name of default sandbox, enable SANDBOXNAME
export SANDBOXNAME=test_sb

#export WORKSPACE=<set it to your root ppe directory. This is required if you
#                  to use build script locally>
export MACHINE=NIMBUS
export BACKING_BUILD=/esw/fips910/Builds/b0421a_1618.910/
export SIMICSOPTIONS="-nre"

