#!/bin/sh

sb_helptext()
{
    echo "SBE Utility Script"

    case $1 in
    workon)
        echo "  Topic 'workon'"
        echo
        echo "  Usage:"
        echo "      sb workon"
        echo
        echo "  Sources necessary environment files for building sbe"
        echo "  and begins a new shell.  The workon may be left via 'exit'."
        echo
        echo "  See also:"
        echo "      customrc"
        ;;
    cmvc)
        echo "  Topic 'Launch CMVC Operation on PPE files'"
        echo
        echo "  Usage:"
        echo "      Refer : $PWD/sbe/build/tools/CommitSbeImageToCMVC.py -h"
        ;;
    prime)
        echo "  Topic 'Compile the PPE files on fips Sandbox'"
        echo
        echo "  Usage:"
        echo "      Refer : $PWD/sbe/build/tools/sbePrime.py -h"
        ;;
    simsetup)
        echo "  Topic 'Patch simics action files on fips Sandbox'"
        echo
        echo "  Usage:"
        echo "      Refer : $PWD/sbe/build/tools/sbePrime.py -h"
        ;;
    *)
        echo "  Usage:"
        echo "      sb <cmd>"
        echo "      sb help [<cmd>|<topic>]"
        echo ""
        echo "  Available Commands:"
        echo "      workon"
        echo "      cmvc"
        echo "      ---------------------------------------------------- "
        echo "      # To check in SBE FW files in CMVC command options # "
        echo "      sb cmvc -f < feature CMVC No > -r <fips release >"
        echo "      sb cmvc -d < defect CMVC No  > -r <fips release >"
        echo "      ---------------------------------------------------- "
        echo ""
        echo "      prime"
        echo ""
        echo "      simsetup"
        echo
    esac
}

sb_workon()
{
    if [ -n "${SBE_INSIDE_WORKON}" ]; then
        echo "Already in a workon."
        exit -1
    else
        export SBE_INSIDE_WORKON=1
        echo "Setting environment variables..."
        source ./env.bash
        echo "Spawning new shell with devtoolset 2..."
        scl enable devtoolset-2 bash
    fi
}

sb_cmvc()
{
    if [ -n "${SBE_INSIDE_WORKON}" ]; then
        echo "Already in a workon.. Continuing" 
        # Launch the CMVC utility 
        str="'$*'"
        echo "User input string : $str"
        $PWD/sbe/build/tools/CommitSbeImageToCMVC.py $*
    else
        echo "Please do workon and re launch..."
    fi

}

sb_prime()
{
    if [ -n "${SBE_INSIDE_WORKON}" ]; then
        echo "Already in a workon.. Continuing"
        str="'$*'"
        echo "User input string : $str"
        $PWD/sbe/build/tools/sbePrime.py $*
    else
        echo "Please do workon and re launch..."
    fi

}

sb_simsetup()
{
    if [ -n "${SBE_INSIDE_WORKON}" ]; then
        echo "Already in a workon.. Continuing"
        str="'$*'"
        echo "User input string : $str"
        $PWD/sbe/build/tools/sbePrime.py -p patch
    else
        echo "Please do workon and re launch..."
    fi

}

if [ 0 == $# ]; then
    sb_helptext
    exit -1
fi

FIRST_PARAM=$1
shift

case ${FIRST_PARAM} in
workon)
    sb_workon $*
    ;;
cmvc)
    sb_cmvc $*
    ;;
prime)
    sb_prime $*
    ;;
simsetup)
    sb_simsetup $*
    ;;
*)
    sb_helptext $*
    exit -1
    ;;
esac
