/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: src/sbefw/measurement/measurement_main.C $                    */
/*                                                                        */
/* OpenPOWER sbe Project                                                  */
/*                                                                        */
/* Contributors Listed Below - COPYRIGHT 2019,2021                        */
/* [+] International Business Machines Corp.                              */
/*                                                                        */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */

#include "sbemtrace.H"
#include "sbemsecuritysetting.H"
#include "sbeglobals.H"

extern "C" {
#include "pk_api.h"
}
#include "sbeXipUtils.H"
////////////////////////////////////////////////////////////////
//// @brief Stacks for Non-critical Interrupts ( timebase, timers )
////////////////////////////////////////////////////////////////
#define INITIAL_PK_TIMEBASE   0
#define MEASUREMENT_NONCRITICAL_STACK_SIZE 512
#define SPI_CLOCK_DELAY_SHIFT     44
#define SPI_CLOCK_DELAY_MASK      0xFFF00FFFFFFFFFFF
#define SPI_CLOCK_DIVIDER_SHIFT   52 
#define SPI_CLOCK_DIVIDER_MASK    0x000FFFFFFFFFFFFF

uint8_t measurment_Kernel_NC_Int_stack[MEASUREMENT_NONCRITICAL_STACK_SIZE];

extern "C"
{
// These variables are declared in linker script to keep track of
// global constructor pointer functions and sbss section.
extern void (*ctor_start_address)() __attribute__ ((section (".rodata")));
extern void (*ctor_end_address)() __attribute__ ((section (".rodata")));
extern uint64_t _sbss_start __attribute__ ((section (".sbss")));
extern uint64_t _sbss_end __attribute__ ((section (".sbss")));
// This function will be used to do any C++ handling required before doing
// any main job. Call to this function should get generated by
// compiler.
// TODO via RTC 152070
// We are also initialising sbss section to zero this function.
// Though it does not do any harm as of now, it is better  if we use loader
// or linker script to zero init sbss section. This way we will be future
// garded if pk  boot uses some static/global data  initialised to
// false in future.

void __eabi()
{
    do
    {
        // Initialise sbss section
        uint64_t *startAddr = &_sbss_start;
        while ( startAddr != &_sbss_end )
        {
            *startAddr = 0;
            startAddr++;
        }
        // Call global constructors
        void(**ctors)() = &ctor_start_address;
        while( ctors != &ctor_end_address)
        {
            (*ctors)();
            ctors++;
        }
    } while (false);
}

/*
 ** API to jump to the boot seeprom.
 */
void jump2boot()
{
    asm(
            "lis %r4, 0xFF80\n"
            "lvd %d0, 0(%r4)\n"
            "lis %r2 , 0x5849\n"
            "ori %r2 , %r2 , 0x5020\n"
            "lis %r3 , 0x5345\n"
            "ori %r3 , %r3, 0x504d\n"
            "cmplwbc 0, 2, %r0, %r2, magic_failed\n"
            "cmplwbc 0, 2, %r1, %r3, magic_failed\n"
            "ori %r4, %r4, 8\n"
            "lvd %d0 , 0(%r4)\n"
            "mtctr %r1\n"
            "bctr\n"
"magic_failed:\n"
            "trap\n"
       );
}
} // end extern "C"

extern uint32_t initializeTPM();
extern uint32_t performTPMSequences();
// SBE Frequency to be used to initialise PK
uint32_t g_sbemfreqency = SBE_REF_BASE_FREQ_HZ;

////////////////////////////////////////////////////////////////
// @brief - main : Measurement Application main
////////////////////////////////////////////////////////////////
int  main(int argc, char **argv)
{
    #define SBEM_FUNC "Measurement main"
    SBEM_ENTER(SBEM_FUNC);
    int l_rc = 0;
    uint64_t rootCtrlReg3 = 0;
    sbe_local_LFR lfrReg;
    do
    {
        // Update the Code Flow status in messaging register 50009
        uint64_t loadValue = (uint64_t)(SBE_CODE_MEASURMENT_PIBMEM_START_MSG)<<32;
        PPE_STVD(0x50009, loadValue);

        //Fetch the default clock divider from LFR
        PPE_LVD(0xc0002040, lfrReg);

        // Fetch the SPI4 Config Registers 
        uint64_t spiClockReg = 0;
        uint64_t spiConfigReg = 0;
        // Unlock SPI4 if it was locked by Hostboot, keep it unlocked
        PPE_LVD(0xc0082, spiConfigReg);
        PPE_STVD(0xc0082, spiConfigReg);

        PPE_LVD(0xc0083, spiClockReg);
        uint8_t clock_delay = 0x80; // default clock delay
        spiClockReg = ( (spiClockReg & SPI_CLOCK_DELAY_MASK) |
                        ((uint64_t)clock_delay << (SPI_CLOCK_DELAY_SHIFT - lfrReg.round_trip_delay)) );
        PPE_STVD(0xc0083, spiClockReg);

        //Check root control register3 bit25 if the PAU DPLL in bypass or not.
        //If not bypass then we can use the 1968MHz chip frequency, if bypass then
        //use 133MHz chip frequency
        PPE_LVD(0x50013, rootCtrlReg3);
        if(!(rootCtrlReg3 & MASK_BIT25))
        {
            g_sbemfreqency = SBE_PAU_DPLL_BASE_FREQ_HZ;
            lfrReg.spi_clock_divider = 48; // Hard-coded basis (1968/40 - 1)
            // Update LFR to match up to the new divider
            PPE_STVD(0xc0002040, lfrReg);

        }
        else
        {
            // g_sbemfrequency and lfr.spi_clock_divider are already updated with
            // 133Mhz and 4 respectively. Just update the TPM Spi clock at this
            // point so that TPM can be accessible. 

            //SPI4
            spiClockReg = 0;
            PPE_LVD(0xc0083, spiClockReg);
            spiClockReg = ( (spiClockReg & SPI_CLOCK_DIVIDER_MASK) |
                            ((uint64_t)lfrReg.spi_clock_divider << SPI_CLOCK_DIVIDER_SHIFT) );
            PPE_STVD(0xc0083, spiClockReg);
        }

        l_rc = pk_initialize((PkAddress)measurment_Kernel_NC_Int_stack,
                             MEASUREMENT_NONCRITICAL_STACK_SIZE,
                             INITIAL_PK_TIMEBASE, // initial_timebase
                             g_sbemfreqency );
        if (l_rc)
        {
            SBEM_ERROR(SBEM_FUNC "pk_initialize failed with rc 0x%08X", l_rc);
            break;
        }
        SBEM_INFO("Completed PK initialization for Measurement");
#if 0
        l_rc = initializeTPM();
        if (l_rc)
        {
            SBEM_ERROR(SBEM_FUNC "initializeTPM failed with rc 0x%08X", l_rc);
            break;
        }
        SBEM_INFO("TPM initialization is complete. Verify SPI and TPM read and write.");
        l_rc = performTPMSequences();
        if (l_rc)
        {
            SBEM_ERROR(SBEM_FUNC "verifySPIandTPM failed with rc 0x%08X", l_rc);
            break;
        }
        SBEM_INFO("Measurment Main is Completed.Loading L1 Loader of Boot Seeprom"); 
#endif
    }while(0);
    SBEM_INFO("LFR = [0x%04X 0x%02X] SBE Freq = 0x%08X", lfrReg.spi_clock_divider, lfrReg.round_trip_delay, g_sbemfreqency);

    sbemSetSecureAccessBit();
    
    jump2boot();
    SBEM_EXIT(SBEM_FUNC);
    return l_rc;
}
