// fapi2AttributeService.C
// This file is generated by perl script fapi2CreateIfAttrService.pl

#include <fapi2AttributeService.H>
//#include <fapi2ChipEcFeature.H>
//#include <fapi2PlatTrace.H>

namespace fapi2
{

ReturnCode fapiGetInitFileAttr(const AttributeId i_id,
                               const Target * i_pTarget,
                               uint64_t & o_val,
                               const uint32_t i_arrayIndex1,
                               const uint32_t i_arrayIndex2,
                               const uint32_t i_arrayIndex3,
                               const uint32_t i_arrayIndex4)
{
    ReturnCode l_rc;

    if (i_id == ATTR_SCRATCH_UINT8_1)
    {
        ATTR_SCRATCH_UINT8_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT8_2)
    {
        ATTR_SCRATCH_UINT8_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT8_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_1)
    {
        ATTR_SCRATCH_UINT32_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_2)
    {
        ATTR_SCRATCH_UINT32_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT64_1)
    {
        ATTR_SCRATCH_UINT64_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT64_2)
    {
        ATTR_SCRATCH_UINT64_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT64_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT8_1)
    {
        ATTR_SCRATCH_INT8_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT8_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT8_2)
    {
        ATTR_SCRATCH_INT8_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT8_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT32_1)
    {
        ATTR_SCRATCH_INT32_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT32_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT32_2)
    {
        ATTR_SCRATCH_INT32_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT32_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT64_1)
    {
        ATTR_SCRATCH_INT64_1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT64_1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_INT64_2)
    {
        ATTR_SCRATCH_INT64_2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_INT64_2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SCRATCH_UINT32_ARRAY)
    {
        ATTR_SCRATCH_UINT32_ARRAY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_ARRAY, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_SCRATCH_UINT32_PERV_ARRAY)
    {
        ATTR_SCRATCH_UINT32_PERV_ARRAY_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SCRATCH_UINT32_PERV_ARRAY, i_pTarget, l_attr);
        o_val = l_attr[i_arrayIndex1];
    }
    else if (i_id == ATTR_REPR_RING)
    {
        ATTR_REPR_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_REPR_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_TIME_RING)
    {
        ATTR_TIME_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_TIME_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_GPTR_RING)
    {
        ATTR_GPTR_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_GPTR_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PLL_RING)
    {
        ATTR_PLL_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PLL_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CORE_REPR_RING)
    {
        ATTR_CORE_REPR_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CORE_REPR_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CORE_TIME_RING)
    {
        ATTR_CORE_TIME_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CORE_TIME_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CORE_GPTR_RING)
    {
        ATTR_CORE_GPTR_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CORE_GPTR_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L2_REPR_RING)
    {
        ATTR_L2_REPR_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L2_REPR_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L2_TIME_RING)
    {
        ATTR_L2_TIME_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L2_TIME_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L2_GPTR_RING)
    {
        ATTR_L2_GPTR_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L2_GPTR_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L3_REPR_RING)
    {
        ATTR_L3_REPR_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L3_REPR_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L3_TIME_RING)
    {
        ATTR_L3_TIME_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L3_TIME_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_L3_GPTR_RING)
    {
        ATTR_L3_GPTR_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_L3_GPTR_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_DPLL_RING)
    {
        ATTR_DPLL_RING_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_DPLL_RING, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_FSI)
    {
        ATTR_PG_FSI_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_FSI, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_PRV)
    {
        ATTR_PG_PRV_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_PRV, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_N0)
    {
        ATTR_PG_N0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_N0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_N1)
    {
        ATTR_PG_N1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_N1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_N2)
    {
        ATTR_PG_N2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_N2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_N3)
    {
        ATTR_PG_N3_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_N3, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_XB)
    {
        ATTR_PG_XB_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_XB, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_MC01)
    {
        ATTR_PG_MC01_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_MC01, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_MC23)
    {
        ATTR_PG_MC23_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_MC23, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_OB0)
    {
        ATTR_PG_OB0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_OB0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_OB1)
    {
        ATTR_PG_OB1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_OB1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_OB2)
    {
        ATTR_PG_OB2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_OB2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_OB3)
    {
        ATTR_PG_OB3_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_OB3, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_PCI0)
    {
        ATTR_PG_PCI0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_PCI0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_PCI1)
    {
        ATTR_PG_PCI1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_PCI1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_PCI2)
    {
        ATTR_PG_PCI2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_PCI2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EQ0)
    {
        ATTR_PG_EQ0_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EQ0, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EQ1)
    {
        ATTR_PG_EQ1_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EQ1, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EQ2)
    {
        ATTR_PG_EQ2_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EQ2, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EQ3)
    {
        ATTR_PG_EQ3_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EQ3, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EQ4)
    {
        ATTR_PG_EQ4_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EQ4, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EQ5)
    {
        ATTR_PG_EQ5_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EQ5, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC00)
    {
        ATTR_PG_EC00_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC00, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC01)
    {
        ATTR_PG_EC01_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC01, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC02)
    {
        ATTR_PG_EC02_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC02, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC03)
    {
        ATTR_PG_EC03_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC03, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC04)
    {
        ATTR_PG_EC04_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC04, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC05)
    {
        ATTR_PG_EC05_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC05, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC06)
    {
        ATTR_PG_EC06_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC06, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC07)
    {
        ATTR_PG_EC07_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC07, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC08)
    {
        ATTR_PG_EC08_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC08, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC09)
    {
        ATTR_PG_EC09_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC09, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC10)
    {
        ATTR_PG_EC10_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC10, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC11)
    {
        ATTR_PG_EC11_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC11, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC12)
    {
        ATTR_PG_EC12_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC12, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC13)
    {
        ATTR_PG_EC13_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC13, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC14)
    {
        ATTR_PG_EC14_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC14, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC15)
    {
        ATTR_PG_EC15_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC15, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC16)
    {
        ATTR_PG_EC16_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC16, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC17)
    {
        ATTR_PG_EC17_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC17, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC18)
    {
        ATTR_PG_EC18_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC18, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC19)
    {
        ATTR_PG_EC19_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC19, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC20)
    {
        ATTR_PG_EC20_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC20, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC21)
    {
        ATTR_PG_EC21_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC21, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC22)
    {
        ATTR_PG_EC22_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC22, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_PG_EC23)
    {
        ATTR_PG_EC23_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_PG_EC23, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_CHIP_UNIT_POS)
    {
        ATTR_CHIP_UNIT_POS_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_CHIP_UNIT_POS, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_FABRIC_SYSTEM_ID)
    {
        ATTR_FABRIC_SYSTEM_ID_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_FABRIC_SYSTEM_ID, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_SYSTEM_IPL_PHASE)
    {
        ATTR_SYSTEM_IPL_PHASE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_SYSTEM_IPL_PHASE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_BACKUP_SEEPROM_SELECT)
    {
        ATTR_BACKUP_SEEPROM_SELECT_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_BACKUP_SEEPROM_SELECT, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else if (i_id == ATTR_MC_SYNC_MODE)
    {
        ATTR_MC_SYNC_MODE_Type l_attr;
        l_rc = FAPI_ATTR_GET(ATTR_MC_SYNC_MODE, i_pTarget, l_attr);
        o_val = l_attr;
    }
    else
    {
        FAPI_ERR("fapiGetInitFileAttr: Unrecognized attr ID: 0x%x", i_id);
        l_rc.setFapiError(FAPI_RC_INVALID_ATTR_GET);
        l_rc.addEIFfdc(0, &i_id, sizeof(i_id));
    }

    if (l_rc)
    {
        if (i_pTarget)
        {
            FAPI_ERR("fapiGetInitFileAttr: Error getting attr ID 0x%x from targType 0x%x",
                     i_id, i_pTarget->getType());
        }
        else
        {
            FAPI_ERR("fapiGetInitFileAttr: Error getting attr ID 0x%x from system target",
                     i_id);
        }
    }

    return l_rc;
}

}
