///
/// @file p9_hcd_cache.H
/// @brief Cache Chiplet Procedure Includes
///
/// *HWP HWP Owner   : David Du       <daviddu@us.ibm.com>
/// *HWP FW Owner    : Sangeetha T S  <sangeet2@in.ibm.com>
/// *HWP Team        : PM
/// *HWP Consumed by : SBE:SGPE
/// *HWP Level       : 1
///

#ifndef __P9_HCD_CACHE_H__
#define __P9_HCD_CACHE_H__

#include <p9_hcd_cache_arrayinit.H>
#include <p9_hcd_cache_chiplet_init.H>
#include <p9_hcd_cache_chiplet_reset.H>
#include <p9_hcd_cache_dpll_setup.H>
#include <p9_hcd_cache_gptr_time_initf.H>
#include <p9_hcd_cache_initf.H>
#include <p9_hcd_cache_occ_runtime_scom.H>
#include <p9_hcd_cache_poweron.H>
#include <p9_hcd_cache_ras_runtime_scom.H>
#include <p9_hcd_cache_repair_initf.H>
#include <p9_hcd_cache_runinit.H>
#include <p9_hcd_cache_scomcust.H>
#include <p9_hcd_cache_scominit.H>
#include <p9_hcd_cache_startclocks.H>

#endif  // __P9_HCD_CACHE_H__
