TOP-C-SOURCES =   
TOP-CPP-SOURCES =
TOP-S-SOURCES = base_ppe_header.S  pm_loader.S

# generated by ppeParseProcSbeFixed.pl
TOP-FIXED-HEADERS += $(IMAGE_SRCDIR)/proc_sbe_fixed_system.H
TOP-FIXED-HEADERS += $(IMAGE_SRCDIR)/proc_sbe_fixed_perv.H
TOP-FIXED-HEADERS += $(IMAGE_SRCDIR)/proc_sbe_fixed_proc_chip.H
TOP-FIXED-HEADERS += $(IMAGE_SRCDIR)/proc_sbe_fixed_core.H
TOP-FIXED-HEADERS += $(IMAGE_SRCDIR)/proc_sbe_fixed_ex.H
TOP-FIXED-HEADERS += $(IMAGE_SRCDIR)/proc_sbe_fixed_eq.H

TOP_OBJECTS = $(TOP-C-SOURCES:.c=.o) $(TOP-CPP-SOURCES:.C=.o) $(TOP-S-SOURCES:.S=.o)

BASE-LOADER-C-SOURCES = base_loader.c
BASE-LOADER-S-SOURCES = base_loader_setup.S

BASE_LOADER_OBJECTS = $(BASE-LOADER-C-SOURCES:.c=.o)  $(BASE-LOADER-S-SOURCES:.S=.o)

OTPROM-LOADER-S-SOURCES = pm_otprom_loader.S
OTPROM_LOADER_OBJECTS = $(OTPROM-LOADER-S-SOURCES:.S=.o)

PPE_FAPI2_DIR_INCL = $(PPE_FAPI2_DIR)/include
# generated by ppeParseAttributeInfo.pl
GEN-PARSEATTRIBUTEINFO += $(PPE_FAPI2_DIR_INCL)/fapi2AttributeIds.H
GEN-PARSEATTRIBUTEINFO += $(PPE_FAPI2_DIR_INCL)/fapi2ChipEcFeature.C
GEN-PARSEATTRIBUTEINFO += $(PPE_FAPI2_DIR_INCL)/fapi2AttributePlatCheck.H
GEN-PARSEATTRIBUTEINFO += $(PPE_FAPI2_DIR_INCL)/fapi2AttributesSupported.html
GEN-PARSEATTRIBUTEINFO += $(PPE_FAPI2_DIR_INCL)/fapi2AttrInfo.csv
GEN-PARSEATTRIBUTEINFO += $(PPE_FAPI2_DIR_INCL)/fapi2AttrEnumInfo.csv

PPE_FAPI2_DIR_SRC = $(PPE_FAPI2_DIR)/src
# generated by ppeCreateAttrGetSetMacros.pl
GEN-CREATEATTRGETSETMACROS += fapi2PlatAttributeService.H.temp
GEN-CREATEATTRGETSETMACROS += $(PPE_FAPI2_DIR_SRC)/fapi2PlatAttributeService.C
GEN-CREATEATTRGETSETMACROS += $(PPE_FAPI2_DIR_INCL)/fapi2PlatAttributeService.H

# generated by ppeCreateIfAttrService.pl
GEN-CREATEIFATTRSERVICE += $(PPE_FAPI2_DIR_INCL)/fapi2AttributeService.C
