///
/// @file p9_hcd_core.H
/// @brief Core Chiplet Procedure Includes
///
/// *HWP HWP Owner   : David Du      <daviddu@us.ibm.com>
/// *HWP FW Owner    : Reshmi Nair   <resnair5@in.ibm.com>
/// *HWP Team        : PM
/// *HWP Consumed by : SBE:CME
/// *HWP Level       : 1
///

#ifndef __P9_HCD_CORE_H__
#define __P9_HCD_CORE_H__

#include <p9_hcd_core_arrayinit.H>
#include <p9_hcd_core_chiplet_init.H>
#include <p9_hcd_core_chiplet_reset.H>
#include <p9_hcd_core_gptr_time_initf.H>
#include <p9_hcd_core_initf.H>
#include <p9_hcd_core_occ_runtime_scom.H>
#include <p9_hcd_core_pcb_arb.H>
#include <p9_hcd_core_poweron.H>
#include <p9_hcd_core_ras_runtime_scom.H>
#include <p9_hcd_core_repair_initf.H>
#include <p9_hcd_core_runinit.H>
#include <p9_hcd_core_scomcust.H>
#include <p9_hcd_core_scominit.H>
#include <p9_hcd_core_startclocks.H>

#endif  // __P9_HCD_CORE_H__
